name: Branch Deleted

on: delete

jobs:
  Prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      path: ${{ steps.create-path.outputs.path }}
    steps:
      - id: create-path
        shell: pwsh
        run: |
          path = ''
          path = ${{ github.event.ref }}
          path = $path.Replace('Del', 'Add')
          echo "path = ${{ path }}" >> $GITHUB_OUTPUT

  Clean:          
    name: Clean
    runs-on: ubuntu-latest
    needs: Prepare
    steps:
      - name: Clean up - Branch
        if: github.event.ref_type == 'branch'
        run: |
          echo "prepared path = ${{ needs.Prepare.outputs.path }}"
          echo "Clean up for BRANCH ${{ github.event.ref }}"

      - name: Clean up TAG
        if: github.event.ref_type == 'tag'
        run: |
          echo "Clean up for TAG ${{ github.event.ref }}"
