name: Branch Deleted

on: delete

jobs:
  Clean:          
    name: Clean
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: GET NAME
        if: github.event.ref_type == 'branch'
        id: get_name
        run: ./.github/utils/test
        shell: pwsh
        
      - name: AS VAR
        if: ${{ env.MY_VAR != '' }}
        run: echo "The value of MY_VAR is $env:MY_VAR"
        shell: pwsh
        
      - name: AS STEP
        if: "${{ steps.get_name.outputs.MY_VAR != '' }}"
        run: echo "The value of MY_VAR is ${{ steps.get_name.outputs.MY_VAR }}"
        shell: pwsh
        
      - name: AS MIX
        if: "${{ env.MY_VAR != '' }}"
        run: echo "The value of MY_VAR is ${{ steps.get_name.outputs.MY_VAR }}"
        shell: pwsh
        

