name: Branch Deleted
on: delete
jobs:
  delete:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Clean up Branch
        if: github.event.ref_type == 'branch'
        run: |
          echo "Clean up for BRANCH ${{ github.event.ref }}"

      - name: Clean up TAG
        if: github.event.ref_type == 'tag'
        run: |
          echo "Clean up for TAG ${{ github.event.ref }}"
