name: Branch Deleted

on: delete

jobs:
  Clean:          
    name: Clean
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: GET NAME
        if: github.event.ref_type == 'branch'
        id: get_name
        run: .github/utils/create_path
        shell: pwsh
        
      - name: AS VAR
        if: ${{ env.deploy_path != '' }}
        run: echo "The value of MY_VAR is $env:deploy_path"
        shell: pwsh
        
      - name: AS STEP
        if: "${{ steps.get_name.outputs.deploy_path != '' }}"
        run: echo "The value of MY_VAR is ${{ steps.get_name.outputs.deploy_path }}"
        shell: pwsh
        
      - name: AS MIX
        if: "${{ env.deploy_path != '' }}"
        run: echo "The value of MY_VAR is ${{ steps.get_name.outputs.deploy_path }}"
        shell: pwsh
        

