name: TEST ON PUSH

on:
  push:
    branches: [ "MAIN" ]
  pull_request:
    branches: [ "MAIN" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v4
      with:
       fetch-depth: 0
       sparse-checkout: |
         .github
         
    - name: test1
      shell: pwsh
      run: |
        Import-Module ./.github/workflows/smth.ps1
        $demo = smth-run
        echo "done"
        echo $demo
