name: TEST ON PUSH

on:
  push:
    branches: [ "MAIN" ]
  pull_request:
    branches: [ "MAIN" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test1
      run: |
        Import-Module ./smth.ps1
        $demo = smth-run
        echo "done"
