name: Remove Source Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if the source branch is not develop or main
        id: check-branch
        run: |
          head_ref="${{ github.event.pull_request.head.ref }}"
          if [[ "$head_ref" != "develop" && "$head_ref" != "MAIN" ]]; then
            echo "DELETE_BRANCH=true" >> $GITHUB_ENV
          else
            echo "DELETE_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Delete the source branch
        if: ${{ env.DELETE_BRANCH == 'true' }}
        run: |
          gh api -X DELETE \
            repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
