name: Branch Merged 

on:
  pull_request:
    types: [closed]
jobs:

  CLOSED:          
    name: PR CLOSED
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: |
          echo "PR WAS CLOSED"
          echo "Clean up for TAG ${{ github.event.ref }}"
          echo "Clean up for TAG ${{ github.event.ref_type }}"
          
