name: Pull Request Closed

on:
  pull_request:
    types: [closed]

jobs:
  remove-branch-job:
    # run job if we merge not MAIN or DEVELOP into other branches 
    # also check that PR was merged 
    if:   ${{ github.event.pull_request.head.ref != 'DEVELOP' && github.event.pull_request.head.ref != 'MAIN' && github.event.pull_request.merged  }} 
    runs-on: ubuntu-latest

    steps:
      - name: remove Release/version/jira-id branch (merged to release/version)
        #Delete RELEASE/{{VERSION}}/{{JIRA-ID}} branch and S3 artifacts when merging into RELEASE/{{VERSION}} branch.
        if: startsWith(github.event.pull_request.head.ref, 'RELEASE/')
        run: |
          head_ref="${{ github.event.pull_request.head.ref }}"
          base_ref="${{ github.event.pull_request.base.ref }}"
          if [[ $head_ref =~ '^RELEASE\/v[\.\d]+/([-\w\d+])$']] && [[ $base_ref =~ '^RELEASE/v[\.\d]+$' ]]; then
            echo "start removing branch ${{ github.event.pull_request.head.ref}} "
            echo "REMOVE_BRANCH=true" >> $GITHUB_ENV
          else
            echo "REMOVE_BRANCH=false" >> $GITHUB_ENV
          fi
          
      - name: remove Release/version branch (merged to MAIN)
        #Delete RELEASE/{{VERSION}} branch and S3 artifacts when merging into MAIN branch.
        if:   ${{ github.event.pull_request.base.ref == 'MAIN' }} && startsWith(github.event.pull_request.head.ref, 'RELEASE/')
        run: |
          head_ref="${{ github.event.pull_request.head.ref }}"
          if [ $head_ref =~'^RELEASE/v[\.\d]+$'  ]; then
            echo "start removing branch ${{ github.event.pull_request.head.ref}} "
            echo "REMOVE_BRANCH=true" >> $GITHUB_ENV
          else
            echo "REMOVE_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: remove User branch
        #Delete user branch when merging into BUILD/{{TERM}} branch.
        if: startsWith(github.event.pull_request.base.ref, 'BUILD/')
        run: |
          base_ref="${{ github.event.pull_request.base.ref }}"
          if [ $base_ref =~ '^BUILD/[-\w\d]+$']; then
            echo "start removing branch ${{ github.event.pull_request.head.ref}} "
            echo "REMOVE_BRANCH=true" >> $GITHUB_ENV
          else
            echo "REMOVE_BRANCH=false" >> $GITHUB_ENV
          fi
          
      - name: remove Build branch
        #Delete BUILD/{{TERM}} branch and S3 artifacts when merging into DEVELOP branch.
        if:  startsWith(github.event.pull_request.head.ref, 'BUILD/') && ${{ github.event.pull_request.base.ref == 'DEVELOP'}} 
        run: |
          head_ref="${{ github.event.pull_request.head.ref }}"
          if [ $head_ref =~ '^BUILD/[-\w\d]+$']; then
            echo "start removing branch ${{ github.event.pull_request.head.ref}} "
            echo "REMOVE_BRANCH=true" >> $GITHUB_ENV
          else
            echo "REMOVE_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: remove SP  branch
        #Delete SP/{{VERSION}}/{{JIRA-ID}} branch and S3 artifacts when merging into SP/{{VERSION}} branch.
        if: startsWith(github.event.pull_request.base.ref, 'SP/') &&  startsWith(github.event.pull_request.head.ref, 'SP/') 
        run: |
          head_ref="${{ github.event.pull_request.head.ref }}"
          base_ref="${{ github.event.pull_request.base.ref }}"
          if [ $head_ref =~ '^SP/v[\.\d]+/([-\w\d+])$' && $base_ref =~ '^SP/v[\.\d]+$' ]; then
            echo "start removing branch ${{ github.event.pull_request.head.ref}} "
            echo "REMOVE_BRANCH=true" >> $GITHUB_ENV
          else
            echo "REMOVE_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: removing head branch
        if:   ${{ env.REMOVE_BRANCH }} 
        run: |
          echo " branch ${{ github.event.pull_request.head.ref}} removed "

    
